const {test,expect}=require('@playwright/test');
async function openGame(page){await page.setViewportSize({width:390,height:844});const errors=[];page.on('pageerror',e=>errors.push(e?.stack||String(e)));await page.goto('http://127.0.0.1:4173/?v=0.73&qa=1',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.FutLiveFootballEngine?.players?.length===14&&window.FutLiveOutOfPlay&&window.FutLiveBoundaryRestarts&&window.FutLiveSetPieces&&window.FutLiveBallContact&&window.FutLiveActionOrientation&&window.FutLiveGoalkeeperLiveness&&window.FutLiveSystemHealth,null,{timeout:12000});return errors}
async function waitPlaying(page){await page.waitForFunction(()=>window.FutLiveMatchState?.phase==='PLAYING'&&!window.FutLiveApp?.isPaused?.(),null,{timeout:12000})}
async function waitFinished(page,n){try{await page.waitForFunction(()=>window.FutLiveMatchState?.phase==='FINISHED',null,{timeout:65000})}catch{const s=await page.evaluate(()=>({phase:window.FutLiveMatchState?.phase,elapsedMs:window.FutLiveMatchState?.elapsedMs,remainingMs:window.FutLiveMatchState?.remainingMs,paused:window.FutLiveApp?.isPaused?.(),setPiece:window.FutLiveSetPieces?.state,ball:{type:window.FutLiveFootballEngine?.ball?.type,owner:window.FutLiveFootballEngine?.ball?.owner?.el?.id||null},health:window.FutLiveSystemHealth?.debug?.(),liveness:window.FutLiveGoalkeeperLiveness?.debug?.()}));throw new Error(`match ${n} timeout: ${JSON.stringify(s)}`)}}

test('architecture health is green',async({page})=>{const errors=await openGame(page),health=await page.evaluate(()=>window.FutLiveSystemHealth.debug());expect(health.ok,JSON.stringify(health)).toBeTruthy();expect(health.failures).toEqual([]);expect(errors).toEqual([])});

test('mobile kickoff has finite continuous positions and working clock',async({page})=>{const errors=await openGame(page),samples=[],started=Date.now();while(Date.now()-started<13000){samples.push(await page.evaluate(()=>({t:performance.now(),phase:window.FutLiveMatchState?.phase,elapsed:window.FutLiveMatchState?.elapsedMs||0,field:window.FutLiveFootballEngine.field(),players:window.FutLiveFootballEngine.players.map(p=>({id:p.el?.id,x:p.x,y:p.y,vx:p.aiVelocity?.x??0,vy:p.aiVelocity?.y??0}))})));if(samples.at(-1).phase==='PLAYING'&&samples.at(-1).elapsed>1200)break;await page.waitForTimeout(50)}expect(samples.some(s=>s.phase==='KICKOFF')).toBeTruthy();expect(samples.some(s=>s.phase==='PLAYING')).toBeTruthy();for(const s of samples){expect(s.field.w).toBeGreaterThan(120);expect(s.field.h).toBeGreaterThan(80);for(const p of s.players)expect([p.x,p.y,p.vx,p.vy].every(Number.isFinite),p.id).toBeTruthy()}const suspicious=[];for(let i=1;i<samples.length;i++){const a=samples[i-1],b=samples[i];if(b.t-a.t>180)continue;for(const p of b.players){const prev=a.players.find(x=>x.id===p.id);if(prev&&Math.hypot(p.x-prev.x,p.y-prev.y)>34&&(a.phase==='KICKOFF'||b.phase==='PLAYING'))suspicious.push(p.id)}}expect(suspicious).toEqual([]);const before=await page.evaluate(()=>window.FutLiveMatchState.elapsedMs);await page.waitForTimeout(1200);const after=await page.evaluate(()=>window.FutLiveMatchState.elapsedMs);expect(after-before).toBeGreaterThan(700);expect(errors).toEqual([])});

test('owned ball stays on rendered forward side',async({page})=>{const errors=await openGame(page);await waitPlaying(page);const s=await page.evaluate(()=>{const e=window.FutLiveFootballEngine,p=e.players.find(x=>x.team==='blue'&&!x.goalkeeper),out=[];e.takePossession(p,'qa-orientation');for(const dir of ['right','left','up','down']){p.ctrl.cancelPendingDirection?.();p.ctrl.play(dir,8,{restart:true});p.facing=dir==='right'?'up':'right';e.syncOwnedBall();out.push({dir,rendered:window.FutLiveBallContact.visualDirection(p),dx:e.ball.x-p.x,dy:e.ball.y-(p.y+27)})}return out});const by=Object.fromEntries(s.map(x=>[x.dir,x]));for(const d of ['right','left','up','down'])expect(by[d].rendered).toBe(d);expect(by.right.dx).toBeGreaterThan(4);expect(by.left.dx).toBeLessThan(-4);expect(by.up.dy).toBeLessThan(-3);expect(by.down.dy).toBeGreaterThan(2);expect(errors).toEqual([])});

test('receiver turns toward incoming pass',async({page})=>{const errors=await openGame(page);await waitPlaying(page);const id=await page.evaluate(()=>{const e=window.FutLiveFootballEngine,r=e.players.find(p=>p.team==='blue'&&!p.goalkeeper),s=e.players.find(p=>p.team==='blue'&&!p.goalkeeper&&p!==r);e.ball.owner=null;e.ball.lastTouch=s;e.ball.intended=r;e.ball.type='pass';e.ball.x=r.x-65;e.ball.y=r.y+27;e.ball.vx=95;e.ball.vy=0;e.ball.pickupLock=performance.now()+700;return r.el.id});await page.waitForTimeout(180);const state=await page.evaluate(id=>{const e=window.FutLiveFootballEngine,p=e.players.find(x=>x.el.id===id);return window.FutLiveActionOrientation.debug(p)},id);expect(state.reason).toBe('RECEIVE_BALL');expect(state.action).toBe('left');expect(errors).toEqual([])});

test('throw-in has single boundary authority and safe goal policy',async({page})=>{const errors=await openGame(page);await waitPlaying(page);const r=await page.evaluate(()=>({set:window.FutLiveSetPieces?.authority,boundary:window.FutLiveOutOfPlay?.authority,policy:window.FutLiveThrowInAIPolicy?.version,duplicate:[...document.scripts].filter(s=>(s.src||'').includes('boundary-restart-system.js')).length}));expect(r.set?.boundaries).toBe('boundary-restart-system');expect(r.boundary).toBe('boundary-restart-system');expect(r.policy).toBeTruthy();expect(r.duplicate).toBe(1);expect(errors).toEqual([])});

test('throw-in visual keeps exact source frame',async({page})=>{const errors=await openGame(page);await waitPlaying(page);const r=await page.evaluate(()=>{const e=window.FutLiveFootballEngine,p=e.players.find(x=>!x.goalkeeper),c=p.ctrl;window.dispatchEvent(new CustomEvent('futlive:throwin-ready',{detail:{taker:p.el.id,side:'top'}}));const before=c.img?.src;window.dispatchEvent(new CustomEvent('futlive:throwin-release',{detail:{taker:p.el.id,side:'top'}}));return{before,after:c.img?.src,active:!!p.throwInVisualLock}});expect(r.active).toBeTruthy();expect(r.before).toBe(r.after);expect(errors).toEqual([])});

test('tackle system can engage a valid ball-side duel',async({page})=>{const errors=await openGame(page);await waitPlaying(page);const r=await page.evaluate(()=>{const e=window.FutLiveFootballEngine,c=e.players.find(p=>p.team==='blue'&&!p.goalkeeper),d=e.players.find(p=>p.team==='red'&&!p.goalkeeper);e.takePossession(c,'qa-duel');d.x=c.x+34;d.y=c.y;d.facing='left';d.lastDir='left';const ok=window.FutLiveTackleSystem?.try?.(d.el.id)||false;return{ok,active:window.FutLiveTackleSystem?.active?.has?.(d)||false}});expect(r.ok||r.active).toBeTruthy();expect(errors).toEqual([])});

test('AI plays full matches without repeated goalkeeper freeze',async({page})=>{test.setTimeout(170000);const errors=await openGame(page);await waitPlaying(page);for(let m=0;m<2;m++){await page.evaluate(()=>{window.FutLiveMatchFlow.setDurationMinutes(.25);if(window.FutLiveMatchState.phase==='FINISHED')window.FutLiveMatchFlow.restartMatch()});if(m>0)await waitPlaying(page);await waitFinished(page,m+1);if(m<1)await page.evaluate(()=>window.FutLiveMatchFlow.restartMatch())}const final=await page.evaluate(()=>window.FutLiveGoalkeeperLiveness.debug()),physical=Object.values(final.goalkeepers).reduce((n,g)=>n+g.physicalRecoveries,0),visual=Object.values(final.goalkeepers).reduce((n,g)=>n+g.visualRecoveries,0);expect(physical,JSON.stringify(final)).toBeLessThanOrEqual(1);expect(visual,JSON.stringify(final)).toBeLessThanOrEqual(2);expect(errors).toEqual([])});

test('throw-in detector enters and leaves set piece',async({page})=>{const errors=await openGame(page);await waitPlaying(page);await page.evaluate(()=>{const e=window.FutLiveFootballEngine,f=e.field(),last=e.players.find(p=>p.team==='blue'&&!p.goalkeeper);e.ball.owner=null;e.ball.lastTouch=last;e.ball.type='free';e.ball.x=(f.left+f.right)/2;e.ball.y=f.bottom-2;e.ball.vx=0;e.ball.vy=220;e.ball.pickupLock=performance.now()+1000});await page.waitForFunction(()=>window.FutLiveMatchState?.phase==='SET_PIECE',null,{timeout:3000});await page.waitForFunction(()=>window.FutLiveMatchState?.phase==='PLAYING'&&!window.FutLiveApp?.isPaused?.(),null,{timeout:10000});expect(errors).toEqual([])});
