(()=>{'use strict';
const VERSION='0.23';
class FutLiveFootballEngine{
  constructor({game='#game',ball='.ball'}={}){this.game=typeof game==='string'?document.querySelector(game):game;this.ballEl=typeof ball==='string'?document.querySelector(ball):ball;this.players=[];this.ball={x:0,y:0,vx:0,vy:0,owner:null,type:'free',curve:0,intended:null,lastTouch:null,pickupLock:0};this.score={blue:1,red:0};this.started=false;this.last=0;this.raf=0;this.actionLock=0;this.ownerSince=0;this.formation={blue:[[.23,.40],[.34,.58],[.42,.29]],red:[[.77,.58],[.66,.36],[.58,.67]]}}
  clamp(v,a,b){return Math.max(a,Math.min(b,v))} rand(a,b){return a+Math.random()*(b-a)} dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
  field(){const r=this.game.getBoundingClientRect(),hud=document.getElementById('liveGiftHud'),hudTop=hud?hud.getBoundingClientRect().top-r.top:r.height*.78;return{w:r.width,h:r.height,left:r.width*.04,right:r.width*.96,top:r.height*.10,bottom:Math.max(r.height*.60,hudTop-18),goalTop:r.height*.36,goalBottom:r.height*.64,goalDepth:26}}
  start(){if(this.started||!this.game||!this.ballEl)return false;const bag=window.FutLivePlayers;if(!bag?.team1?.length||!bag?.team2?.length)return false;const ctrls=[...bag.team1,...bag.team2],r=this.game.getBoundingClientRect();this.players=ctrls.map((ctrl,i)=>{const team=i<3?'blue':'red',slot=i%3,pos=this.formation[team][slot],personality=['creator','runner','finisher'][slot];ctrl.el.style.right='auto';return{ctrl,el:ctrl.el,team,slot,personality,x:r.width*pos[0],y:r.height*pos[1],radius:13,bodyMass:personality==='runner'?1.03:1,baseSpeed:this.rand(78,92),speed:0,lastDir:'idle',nextThink:0,skill:{control:this.rand(.58,.90),pass:this.rand(.55,.89),shoot:this.rand(.55,.91),defend:this.rand(.48,.84),vision:this.rand(.52,.90),composure:this.rand(.46,.88),curve:this.rand(.35,.82)}}});this.players.forEach(p=>p.speed=p.baseSpeed*(p.personality==='runner'?1.07:1));this.resetBall();this.renderScore();this.started=true;this.last=performance.now();this.raf=requestAnimationFrame(t=>this.loop(t));window.FutLiveFootballEngine=this;const v=document.querySelector('.version');if(v)v.textContent='BETA '+VERSION;return true}
  resetBall(){const f=this.field();this.ball={x:(f.left+f.right)/2,y:(f.top+f.bottom)/2,vx:0,vy:0,owner:null,type:'free',curve:0,intended:null,lastTouch:null,pickupLock:0};this.ownerSince=0;this.players.forEach(p=>{const q=this.formation[p.team][p.slot];p.x=f.w*q[0];p.y=f.h*q[1];p.nextThink=performance.now()+this.rand(80,280);p.ctrl.idle()});this.resolvePlayerCollisions(f,3);this.paint()}
  dirFor(dx,dy){if(Math.abs(dx)>Math.abs(dy))return dx>0?'right':'left';return dy>0?'down':'up'}
  moveToward(p,tx,ty,speed,dt){const dx=tx-p.x,dy=ty-p.y,d=Math.hypot(dx,dy);if(d<1){if(p.lastDir!=='idle'){p.lastDir='idle';p.ctrl.idle()}return d}const s=Math.min(d,speed*dt);p.x+=dx/d*s;p.y+=dy/d*s;const dir=this.dirFor(dx,dy);if(p.lastDir!==dir){p.lastDir=dir;p.ctrl.move(dir)}return d}
  nearest(team,target,exclude=null){let p=null,d=Infinity;for(const q of this.players)if(q.team===team&&q!==exclude){const n=this.dist(q,target);if(n<d){d=n;p=q}}return{p,d}}
  mates(team,e=null){return this.players.filter(p=>p.team===team&&p!==e)} opponents(team){return this.players.filter(p=>p.team!==team)}
  resolvePlayerCollisions(f,passes=2){for(let k=0;k<passes;k++){for(let i=0;i<this.players.length;i++)for(let j=i+1;j<this.players.length;j++){const a=this.players[i],b=this.players[j],min=a.radius+b.radius;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d>=min)continue;if(d<.001){const ang=(i*2.17+j*1.31);dx=Math.cos(ang);dy=Math.sin(ang);d=1}const nx=dx/d,ny=dy/d,over=min-d;const ownerA=this.ball.owner===a,ownerB=this.ball.owner===b;let pushA=.5,pushB=.5;if(ownerA&&!ownerB){pushA=.32;pushB=.68}else if(ownerB&&!ownerA){pushA=.68;pushB=.32}const softness=.72;a.x-=nx*over*pushA*softness;a.y-=ny*over*pushA*softness;b.x+=nx*over*pushB*softness;b.y+=ny*over*pushB*softness;a.x=this.clamp(a.x,f.left+a.radius,f.right-a.radius);a.y=this.clamp(a.y,f.top+a.radius,f.bottom-a.radius);b.x=this.clamp(b.x,f.left+b.radius,f.right-b.radius);b.y=this.clamp(b.y,f.top+b.radius,f.bottom-b.radius)}}}
  syncOwnedBall(){const p=this.ball.owner;if(!p)return;const attack=p.team==='blue'?1:-1;this.ball.x=p.x+attack*14;this.ball.y=p.y+31}
  takePossession(p,reason='control'){this.ball.owner=p;this.ball.vx=this.ball.vy=0;this.ball.curve=0;this.ball.type='owned';this.ball.intended=null;this.ball.lastTouch=p;this.ownerSince=performance.now();p.nextThink=this.ownerSince+this.rand(260,760);this.game.dataset.lastAction=reason}
  choosePassTarget(c){const attack=c.team==='blue'?1:-1,opps=this.opponents(c.team);let best=null,score=-1e9;for(const m of this.mates(c.team,c)){const forward=(m.x-c.x)*attack,open=Math.min(...opps.map(o=>this.dist(m,o))),lane=Math.abs(m.y-c.y),s=forward*(.45+c.skill.vision*.55)+open*(.42+c.skill.vision*.45)-lane*.10+this.rand(-34,34)+(m.personality==='runner'?18:0);if(s>score){score=s;best=m}}return best}
  pass(c,t){if(!t)return;const attack=c.team==='blue'?1:-1,lead=(t.personality==='runner'?this.rand(18,42):this.rand(4,20))*attack,tx=t.x+lead+this.rand(-26,26)*(1-c.skill.pass),ty=t.y+this.rand(-48,48)*(1-c.skill.pass),dx=tx-c.x,dy=ty-c.y,d=Math.hypot(dx,dy)||1,s=Math.min(292,180+d*.34+(c.skill.pass-.5)*42);this.ball.owner=null;this.ball.type='pass';this.ball.intended=t;this.ball.lastTouch=c;this.ball.pickupLock=performance.now()+190;this.ball.x=c.x+attack*11;this.ball.y=c.y+31;this.ball.vx=dx/d*s;this.ball.vy=dy/d*s;this.ball.curve=0;this.actionLock=performance.now()+this.rand(420,620);this.game.dataset.lastAction='pass'}
  shoot(c,f){const attack=c.team==='blue'?1:-1,goalX=c.team==='blue'?f.right+f.goalDepth:f.left-f.goalDepth,roll=Math.random();let kind,power,spread;if(roll<.30){kind='weak';power=this.rand(205,250);spread=.50}else if(roll<.76){kind='medium';power=this.rand(275,340);spread=.70}else{kind='strong';power=this.rand(355,430);spread=.92}const pressure=this.nearest(c.team==='blue'?'red':'blue',c).d,panic=pressure<32?(32-pressure)/32:0,targetY=(f.goalTop+f.goalBottom)/2+(Math.random()-.5)*(f.goalBottom-f.goalTop)*spread*(1.35-c.skill.shoot*.65+panic*.55),curved=Math.random()<(.18+c.skill.curve*.38),dx=goalX-c.x,dy=targetY-c.y,d=Math.hypot(dx,dy)||1;this.ball.owner=null;this.ball.type='shot-'+kind+(curved?'-curve':'-straight');this.ball.curve=curved?(Math.random()<.5?-1:1)*this.rand(.34,.72)*c.skill.curve:0;this.ball.intended=null;this.ball.lastTouch=c;this.ball.pickupLock=performance.now()+250;this.ball.x=c.x+attack*15;this.ball.y=c.y+31;this.ball.vx=dx/d*power;this.ball.vy=dy/d*power;this.actionLock=performance.now()+this.rand(620,840);c.ctrl.kick();c.lastDir='kick';this.game.dataset.lastAction=this.ball.type}
  freeAI(dt,f){const b=this.nearest('blue',this.ball),r=this.nearest('red',this.ball),now=performance.now();for(const n of [b,r])if(n.p&&now>=n.p.nextThink)this.moveToward(n.p,this.ball.x+this.ball.vx*.12,this.ball.y+this.ball.vy*.10,n.p.speed*1.12,dt);const chase=[b.p,r.p];for(const p of this.players)if(!chase.includes(p)){const h=this.formation[p.team][p.slot],attack=p.team==='blue'?1:-1,w=Math.sin(now/700+p.slot*2+(p.team==='red'?1:0))*18;this.moveToward(p,f.w*h[0]+(this.ball.x-f.w*.5)*.13+attack*(p.slot-1)*10,f.h*h[1]+(this.ball.y-f.h*.5)*.08+w,p.speed*.60,dt)}if(now>=this.ball.pickupLock){for(const n of [b,r].filter(x=>x.p&&x.d<23).sort((x,y)=>x.d-y.d))if(Math.random()<n.p.skill.control*(n.d<15?.94:.72)){this.takePossession(n.p,'recovery');break}}}
  ownedAI(dt,f){const c=this.ball.owner;if(!c)return;const attack=c.team==='blue'?1:-1,goalX=c.team==='blue'?f.right:f.left,goalY=(f.goalTop+f.goalBottom)/2,enemy=c.team==='blue'?'red':'blue',now=performance.now(),press=this.nearest(enemy,c).p;if(press){const e=this.rand(-12,12)*(1-press.skill.defend);this.moveToward(press,c.x-attack*(8+e),c.y+e,press.speed*(.90+press.skill.defend*.20),dt)}const mates=this.mates(c.team,c),defs=this.opponents(c.team).filter(p=>p!==press);mates.forEach((m,i)=>{const lane=i===0?f.top+(f.bottom-f.top)*.27:f.top+(f.bottom-f.top)*.73,surge=(m.personality==='runner'?105:72)+i*20;this.moveToward(m,this.clamp(c.x+attack*surge,f.left+28,f.right-28),lane,m.speed*(m.personality==='runner'?.92:.76),dt)});defs.forEach((d,i)=>{const mark=mates[i%mates.length]||c,aw=d.skill.defend,slack=(1-aw)*this.rand(18,55);this.moveToward(d,(c.x+mark.x)*.5-attack*(8+slack),(c.y+mark.y)*.5+this.rand(-22,22)*(1-aw),d.speed*(.60+aw*.18),dt)});this.moveToward(c,goalX-attack*this.rand(58,105),goalY+Math.sin(now/520+c.slot*1.7)*this.rand(18,42)*(1-c.skill.composure*.35),c.speed*(.91+c.skill.control*.12),dt);this.syncOwnedBall();const pressure=press?this.dist(press,c):999,possess=now-this.ownerSince,goalDist=Math.abs(goalX-c.x),target=this.choosePassTarget(c);if(press&&pressure<27&&now>this.actionLock){const tackle=(.12+press.skill.defend*.28)-(.08+c.skill.control*.18);if(Math.random()<dt*1.45*Math.max(.06,tackle+.16)){this.takePossession(press,'steal');this.actionLock=now+this.rand(420,720);return}}if(now<c.nextThink)return;const passNeed=(pressure<this.rand(35,60)&&possess>this.rand(380,850))||(possess>this.rand(1250,2300)&&Math.random()<.55+(c.personality==='creator'?.22:0));if(passNeed&&target&&now>this.actionLock&&Math.random()<.55+c.skill.pass*.35){this.pass(c,target);return}const range=f.w*(c.personality==='finisher'?.54:.46),close=goalDist<f.w*.25;if(goalDist<range&&possess>this.rand(420,900)&&(close||Math.random()<.22+c.skill.shoot*.42)&&now>this.actionLock){this.shoot(c,f);return}c.nextThink=now+this.rand(260,780)}
  intercept(dt){if(this.ball.owner||performance.now()<this.ball.pickupLock)return;const speed=Math.hypot(this.ball.vx,this.ball.vy);let best=null,bd=Infinity;for(const p of this.players){if(p===this.ball.lastTouch&&speed>120)continue;const d=this.dist(p,this.ball);if(d<bd){bd=d;best=p}}if(!best)return;if(this.ball.type==='pass'&&best===this.ball.intended&&bd<22&&Math.random()<.42+best.skill.control*.50-Math.min(.20,speed/1400)){this.takePossession(best,'pass-received');return}if(this.ball.type==='pass'&&best.team!==this.ball.lastTouch?.team&&bd<19&&Math.random()<dt*(1.0+best.skill.defend*1.8+best.skill.vision*.5)){this.takePossession(best,'interception');return}if(speed<125&&bd<19&&Math.random()<.32+best.skill.control*.55)this.takePossession(best,'recovery')}
  physics(dt,f){if(this.ball.owner)return;const speed=Math.hypot(this.ball.vx,this.ball.vy);if(this.ball.curve&&speed>30){const a=this.ball.curve*dt,nx=this.ball.vx*Math.cos(a)-this.ball.vy*Math.sin(a),ny=this.ball.vx*Math.sin(a)+this.ball.vy*Math.cos(a);this.ball.vx=nx;this.ball.vy=ny}this.ball.x+=this.ball.vx*dt;this.ball.y+=this.ball.vy*dt;const drag=this.ball.type.startsWith('shot')?.76:.60;this.ball.vx*=Math.pow(drag,dt);this.ball.vy*=Math.pow(drag,dt);if(this.ball.y<f.top){this.ball.y=f.top;this.ball.vy=Math.abs(this.ball.vy)*.70}if(this.ball.y>f.bottom){this.ball.y=f.bottom;this.ball.vy=-Math.abs(this.ball.vy)*.70}const inGoal=this.ball.y>=f.goalTop&&this.ball.y<=f.goalBottom;if(this.ball.x>f.right){if(inGoal&&this.ball.x>=f.right+f.goalDepth){this.goal('blue');return}else if(!inGoal){this.ball.x=f.right;this.ball.vx=-Math.abs(this.ball.vx)*.62}}if(this.ball.x<f.left){if(inGoal&&this.ball.x<=f.left-f.goalDepth){this.goal('red');return}else if(!inGoal){this.ball.x=f.left;this.ball.vx=Math.abs(this.ball.vx)*.62}}this.intercept(dt)}
  goal(team){this.score[team]++;this.renderScore();this.game.dataset.lastGoal=team;this.ball.x=this.ball.y=-999;this.ball.vx=this.ball.vy=0;this.ball.owner=null;setTimeout(()=>this.resetBall(),650)} renderScore(){const e=document.querySelector('.scorebox b');if(e)e.innerHTML=`${this.score.blue} &nbsp;×&nbsp; ${this.score.red}`}
  paint(){const f=this.field();for(const p of this.players){p.x=this.clamp(p.x,f.left+p.radius,f.right-p.radius);p.y=this.clamp(p.y,f.top+p.radius,f.bottom-p.radius);p.el.style.left=p.x+'px';p.el.style.top=p.y+'px'}this.ballEl.style.left=this.ball.x+'px';this.ballEl.style.top=this.ball.y+'px';this.ballEl.dataset.type=this.ball.type}
  step(dt){const f=this.field();if(this.ball.owner)this.ownedAI(dt,f);else this.freeAI(dt,f);this.resolvePlayerCollisions(f,3);if(this.ball.owner)this.syncOwnedBall();this.physics(dt,f);this.paint()}
  loop(t){if(!this.started)return;const dt=Math.min(.034,Math.max(.001,(t-this.last)/1000));this.last=t;if(!this.game.classList.contains('is-paused'))this.step(dt);this.raf=requestAnimationFrame(n=>this.loop(n))} stop(){this.started=false;cancelAnimationFrame(this.raf)}
}
function boot(){const attempt=()=>{const e=new FutLiveFootballEngine();if(!e.start())setTimeout(attempt,120)};attempt()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.FutLiveFootballEngineClass=FutLiveFootballEngine;
})();